scikit-learn 패키지 : sklearn으로 명명
sklearn.datasets : 사이킷런에서 자체적으로 제공하는 데이터 세트를 생성하는 모듈의 모임
sklearn.tree : 트리 기반 ML 알고리즘을 구현한 클래스의 모임
sklearn.model_selection : 학습 데이터 / 검증 데이터 / 예측 데이터로 데이터를 분리하고나 최적의 하이퍼파라미터로 평가하기 위한 다양한 모임의 모임
load_iris : 붓꽃 데이터
DecisionTreeClassifier : 의사 결정 트리 알고리즘
train_test_split : 데이터를 학습 데이터와 테스트 데이터로 분리

In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [17]:
import pandas as pd

# 붗꽃 데이터 세트 로딩
iris=load_iris()

# iris.data는 iris 데이터 세트에서 feature 데이터를 numpy로 가지고 있다.
iris_data=iris.data
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [18]:
# iris.target는 iris 데이터 세트에서 label 데이터를 numpy로 가지고 있다.
iris_label=iris.target
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

# iris 데이터 세트를 보기 위해 dataframe으로 변환
iris_df=pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0


결론적으로, iris데이터는 다음과 같다.
sepal length, sepal width, petal length, petal width 값이 feature 값이고, 이것이 iris.data 값이다.
이 feature 값을 가지고, label 분류를 한다. label은 우리가 맞춰야 하는 꽃의 종류고, iris.target으로 표현된다.
label 값은 0(setosa), 1(versicolor), 2(virginica)가 있다.
우리는 결론적으로 feature 값을 가지고 훈련시켜서 label값을 맞춰야 한다.

우리는 이제 모델 학습을 시킬 것이다.
지도 학습의 방법으로 모델 학습을 시킬 것이기 때문에, 데이터를 나눠야 한다.
iris_data (꽃의 특징 데이터)를 X_train, X_test로 분리할 것이다.
iris_label (target : 꽃의 이름 데이터)를 y_train, y_test로 분리할 것이다.
맨 처음에 X_train, y_train 데이터로 모델의 학습을 진행한다.
그 다음에 y_train 데이터를 넣으면 모델이 판단한 target 데이터가 나올 것이고, 이것을 y_test데이터와 비교하여 모델의 성능을 따질 것이다.

In [21]:
# train_test_split을 통해 데이터를 나눈다. test_size=0.2는 train data를 80%, test data를 20%로 나눈다는 뜻이다.
# random state는 호출할 때마다 같은 학습/테스트 용 데이터 세트를 생성하기 위한 작업이다.
# 이 값이 지정되어 있으면 호출할 때마다 데이터 세트가 같게 나오고, 지정하지 않으면 다르게 나온다.
X_train, X_test, y_train, y_test = train_test_split (iris_data, iris_label, test_size=0.2, random_state=11)

In [23]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

fit(a,b) 메서드 : a를 feature, b를 target으로 해서 모델의 학습을 수행한다.

predict(a) 메서드 : a라는 feature 데이터를 가지고 target을 맞춘다. (전에 fit 메서드로 모델은 학습을 완료한 상태이다.)

sklearn.metrics : 사이킷런 라이브러리에서 모델의 성능을 평가할 때 사용하는 모듈.
분류(classification) 관련 지표 : accuracy_score(정확도, 전체 중에서 맞춘 비율), precision_score, recall_score 등
회귀(regression) 관련 지표 : mean_squared_error 등
accuracy_score(a,b) : b라는 데이터 중에서 a와 맞는 비율 (a가 정답이고 b가 모델이 예측한 데이터이다.)

In [25]:
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [28]:
pred=dt_clf.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9333


사이킷런은 ML 모델 지도학습을 위해서 fit()을, 학습된 모델의 예측을 위해 predict() 메서드를 제공함.

Estimater (지도학습의 모든 알고리즘을 구현한 클래스) : Classifier, Regressor로 나뉨.

1. Classifier (분류 알고리즘) : DecisionTreeClassifier, RandomForestClassifier, GradientBoostingClassifier 등
2. Regressor (회귀 알고리즘) : LinearRegression, Ridge, Lasso, RandomforestRegressor, GradientBoostingRegressor

비지도학습을 위해서는 fit(), transform() 메서드를 제공. 
fit() 메서드는 입력 데이터의 형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞추는 작업
transform() 메서드는 입력 데이터의 차원 변환, 클러스터링, 특징 추출 등의 실제 작업

사이킷런의 주요 모듈
1. 예제 데이터 : sklearn.datasets
2. 피처 처리 : sklearn.preprocessing / sklearn.feature_selection / sklearn.feature_extraction
3. 피처 처리&차원 축소 : sklearn.decomposition
4. 데이터 분리,검증,파라미터 튜닝 : sklearn.model_selection
5. 평가 : sklearn.metrics
6. ML 알고리즘 : sklearn.neighbors / sklearn.tree 등
7. 유틸리티 : sklearn.pipeline

사이킷런에는 예제로 활용할 수 있는 내장 dataset이 있음.
ex) datasets.load_iris() : 붓꽃 데이터 세트

fetch 계열의 명령을 통해 외부에서 내려받아 사용할 수도 있음.

datasets.make을 통해 데이터 세트를 만들 수도 있다.

분류나 회귀를 위한 연습용 예제 데이터는 보통 딕셔너리 형태로 되어 있다. sklearn에서는 bunch 클래스로 표기된다.
bunch class는 딕셔너리 형태와 유사한 데이터이다.

data(ndarray타입) : feature의 데이터 세트
target(ndarray타입) : 분류 시 label 값, 회귀일 때는 숫자 결괏값 데이터 세트
target_names(ndarray, list타입) : 개별 레이블의 이름 ('setosa' 'versicolor' 'virginica')
feature_names(ndarray, list타입) : feature의 이름 ('sepal length' 'sepal width' 'petal length' 'petal width')
DESCR : 데이터 세트에 대한 설명과 각 feature의 설명

In [32]:
from sklearn.datasets import load_iris
iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [33]:
keys=iris_data.keys()
print('붗꽃 데이터 세트의 키들:', keys)

붗꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [34]:
print('feature_names의 type:', type(iris_data.feature_names))
print('feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

feature_names의 type: <class 'list'>
feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [35]:
print('target_names의 type:', type(iris_data.target_names))
print('target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']


In [39]:
print('data의 type:', type(iris_data.data))
print('data의 shape:', iris_data.data.shape)
print(iris_data.data)

data의 type: <class 'numpy.ndarray'>
data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1

In [38]:
print('target의 type:', type(iris_data.target))
print('target의 shape:', iris_data.target.shape)
print(iris_data.target)

target의 type: <class 'numpy.ndarray'>
target의 shape: (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
