### 넘파이 ndarray 개요

In [2]:
import numpy as np

In [3]:
array1=np.array([1,2,3])
print('array1 type',type(array1))

array1 type <class 'numpy.ndarray'>


In [9]:
print('array1 array 형태:',array1.shape)

array1 array 형태: (3,)


1차원array로 3개의 데이터를 가짐

In [12]:
array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type',type(array2))

array2 type <class 'numpy.ndarray'>


In [14]:
print('array2 array 형태',array2.shape)

array2 array 형태 (2, 3)


2차원array로 3개의 칼럼에 2개의 로우로 이뤄짐, 6개의 data가짐

In [18]:
array3=np.array([[1,2,3]])
print('array3 type:',type(array3))

array3 type: <class 'numpy.ndarray'>


In [19]:
print('array3 array 형태:',array3.shape)

array3 array 형태: (1, 3)


1개의 로우와 3개의 칼럼으로 구성된 2차원 데이터

In [20]:
print('array1:{0}차원,array2:{1}차원,array3:{2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1:1차원,array2:2차원,array3:2차원


리스트 []는 1차원,리스트안의 리스트[[]]는 2차원

### ndarry의 데이터 타입

ndarray내 데이터타입은 같은 데이터 타입만 가능(ex. int,float같이 못있음)

In [27]:
list1=[1,2,3]
print(type(list1))

<class 'list'>


In [28]:
array1=np.array(list1)
print(type(array1))

<class 'numpy.ndarray'>


In [29]:
print(array1,array1.dtype)

[1 2 3] int32


서로 다른 데이터 타입 가지는 리스트를 ndarray로 변환 시 데이터 크기가 더 큰 데이터 타입으로 형변환 일괄 적용

In [30]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

['1' '2' 'test'] <U11


숫자형 값 1,2 -> 문자열 값 '1','2'로 변환

In [31]:
list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

[1. 2. 3.] float64


int 1,2 -> float 1. ,2.

ndarray내 데이터 값의 타입 변경 : astype()
- 대용량 데이터의 ndarray만들 때 -> 메모리 절약

In [34]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

[1. 2. 3.] float64


In [35]:
array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

[1 2 3] int32


In [36]:
arrray_float1=np.array([1.1,2.1,3.1])
array_int2=array_float.astype('int32')
print(array_int2,array_int2.dtype)

[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange,zeros,ones

특정 크기,차원을 가진 ndarray를 연속값/0/1로 초기화해 쉽게 생성해야 할 경우
arrange(),zeros(),ones()로 쉽게 ndarray를 생성

테스트용으로 데이터 만들거나 대규모 데이터 일괄적 초기화 할 경우

In [38]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


zeros() : 함수 인자로 튜플형태의 shape값을 입력 시 모든 값을 0으로 채운 shape을 가진 ndarray로 반환

In [39]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


ones() : 함수 인자로부터 튜플 형태의 shape값 입력 시 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환

함수인자로 dtype설정x-> float64형의 데이터로 ndarray를 채움

In [40]:
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

ndarray를 특정 차원,크기로 변환
변환하는 크기를 함수 인자로 부여함

In [41]:
array1=np.arange(10)
print('array1:\n',array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [42]:
array2=array1.reshape(2,5)
print('array2:\n',array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [43]:
array3=array1.reshape(5,2)
print('array3:\n',array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [44]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

지정된 사이즈로 변경 불가 시 오류 발생

-1을 인자로 사용 시 ndarray와 호환되는 새로운 shape로 변환해줌

In [45]:
array1=np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
array2=array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array2 shape: (2, 5)


고정된 5개 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변환
-> 10개의 1차원 데이터와 호환될 수 있는 고정된 5개 칼럼에 맞는 로우 개수는 2이므로 2*5의 2차원ndarray로 변환

In [48]:
array3=array1.reshape(5,-1)
print('array3 shape:',array3.shape)

array3 shape: (5, 2)


고정된 5개의 로우에 맞는 컬럼은 2이므로 5*2의 2차원 ndarray로 변환

In [49]:
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

10개의 1차원 데이터를 고정된 4개의 칼럼가진 로우로는 변경 x

reshape(-1,1)같은걸로 자주 사용
원본 ndarray가 어떤 형태라도 2차원,여러개의 로우를 가지되 반드시 1개 칼럼 가진 ndarray로 변환됨을 보장

In [51]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [52]:
#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [53]:
#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]


In [54]:
print('array6 shape:',array6.shape)

array6 shape: (8, 1)


ndarray는 tolist()를 이용해 리스트 자료형으로 변환 가능

### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱

- 단일값 추출

In [3]:
array1=np.arange(start=1,stop=10)
print('array1:',array1)

array1: [1 2 3 4 5 6 7 8 9]


In [5]:
value=array1[2]
print('value:',value)
print(type(value))

value: 3
<class 'numpy.int32'>


인덱스는 0부터 시작하므로 array1[2]는 3번째 위치의 데이터 값,
type은 ndarray내의 데이터값이 됨

In [7]:
print('맨뒤의 값:',array1[-1],'맨뒤에서두번째값:',array1[-2])

맨뒤의 값: 9 맨뒤에서두번째값: 8


- 단일 인덱스를 이용해 ndarray내 데이터 값 수정하기

In [8]:
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


- 다차원 ndarray에서 단일값 추출

In [9]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print('(row=0,col=0) index 가리키는 값:',array2d[0,0])

(row=0,col=0) index 가리키는 값: 1


In [11]:
print('(row=0,col=1) index 가리키는 값:',array2d[0,1])

(row=0,col=1) index 가리키는 값: 2


In [12]:
print('(row=1,col=0) index 가리키는 값:',array2d[1,0])

(row=1,col=0) index 가리키는 값: 4


In [14]:
print('(row=2,col=2) index 가리키는 값:',array2d[2,2])

(row=2,col=2) index 가리키는 값: 9


- axis 0: 로우방향의 축
- axis 1: 칼럼방향의 축

### 슬라이싱

슬라이싱,팬시 인덱싱, 불린 인덱싱으로 추출된 데이터셋은 모두 ndarray타입

In [15]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [16]:
array1=np.arange(start=1,stop=10)
array4=array1[:3]
print(array4)

[1 2 3]


In [19]:
array5=array1[3:]
print(array5)

[4 5 6 7 8 9]


In [20]:
array6=array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]


- 2차원 슬라이싱

In [21]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print('array2d[0:2,0:2]\n',array2d[0:2,0:2])

array2d[0:2,0:2]
 [[1 2]
 [4 5]]


In [23]:
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])

array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]


In [24]:
print('array2d[1:3,:]\n',array2d[1:3,:])

array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]


In [25]:
print('array2d[:,:]\n',array2d[:,:])

array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print('array2d[:2,1:]\n',array2d[:2,1:])

array2d[:2,1:]
 [[2 3]
 [5 6]]


In [27]:
print('array2d[:2,0]\n',array2d[:2,0])

array2d[:2,0]
 [1 4]


2차원 ndarray에서 오는 뒤에오는 인덱스를 없에면 1차원 ndarray를 반환

In [28]:
print(array2d[0])

[1 2 3]


In [29]:
print(array2d[1])

[4 5 6]


In [30]:
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:',array2d[1].shape)

array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱

리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [31]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

In [32]:
array3d=array2d[[0,1],2]
print('array2d[[0,1],2] ->',array3d.tolist())

array2d[[0,1],2] -> [3, 6]


로우축에 팬시인덱싱인 [0,1]을 칼럼축에 단일값 인덱싱2를 적용 -> (0,2),(1,2)로 적용되어 [3,6]반환

In [33]:
array4d=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]->',array4d.tolist())

array2d[[0,1],0:2]-> [[1, 2], [4, 5]]


((0,0),(0,1)),(1,0),(1,1))인덱싱 적용 -> [[1,2],[4,5]]반환

In [34]:
array5=array2d[[0,1]]
print('array2d[[0,1]]->',array5.tolist())

array2d[[0,1]]-> [[1, 2, 3], [4, 5, 6]]


((0,:),(1,:))인덱싱 적용 -> [[1,2,3],[4,5,6]]반환

### 불린 인덱싱

ndarray의 인덱스를 지정하는 []내에 조건문 그대로 기재함

In [36]:
array1d=np.arange(start=1,stop=10)
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과값:',array3)

array1d>5 불린 인덱싱 결과값: [6 7 8 9]


In [37]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

ㄴ> 이 조건이 []에 들어가면 False무시하고 True해당하는거만 데이터셋으로 반환

In [38]:
boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:',array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [39]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링한 결과:',array4)

일반 인덱스로 필터링한 결과: [6 7 8 9]


### 행렬의 정렬 = sort()와 argsort()

np.sort()는 원 행렬 유지한채 원행렬의 정렬된 행렬을 반환
ndarray.sort()는 원행렬 자체를 정렬한 형태로 변환하며 반환값은 None

In [40]:
org_array=np.array([3,1,9,5])
print('원본행렬:',org_array)

sort_array1=np.sort(org_array)
print('np.sort()호출 후 반환된 정렬 행렬:',sort_array1)

원본행렬: [3 1 9 5]
np.sort()호출 후 반환된 정렬 행렬: [1 3 5 9]


In [41]:
print('np.sort()호출 후 원본 행렬:',org_array)

np.sort()호출 후 원본 행렬: [3 1 9 5]


In [42]:
sort_array2=org_array.sort()
print('org_array.sort()호출 후 반환된 행렬:',sort_array2)
print('org_array.sort()호출 후 원본 행렬:',org_array)

org_array.sort()호출 후 반환된 행렬: None
org_array.sort()호출 후 원본 행렬: [1 3 5 9]


In [45]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


- 행렬이 2차원 이상일 경우 axis축값 설정으로 로우/칼럼방향으로 정렬 수행 가능

In [46]:
array2d=np.array([[8,12],[7,1]])
sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼방향으로 정렬:\n;',sort_array2d_axis1)

로우방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼방향으로 정렬:
; [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기

원본행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요할 때 np.argsort() 사용
-> 정렬 행렬의 원본 행렬 인덱스를 nparray형으로 반환

In [47]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬정렬시 원본 행렬의 인덱스',sort_indices)

<class 'numpy.ndarray'>
행렬정렬시 원본 행렬의 인덱스 [1 0 3 2]


In [48]:
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

행렬내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


- 넘파이의 데이터 추출에서 많이 사용됨

In [50]:
import numpy as np
name_array=np.array(['john','mike','sarah','kate','samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적옮차순으로 naem_array이름출력:',name_array[sort_indices_asc])

성적오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적옮차순으로 naem_array이름출력: ['john' 'sarah' 'samuel' 'mike' 'kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

- 행렬 내적(행렬곱)

In [51]:
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])

In [52]:
dot_product=np.dot(A,B)
print('행렬내적 결과:\n',dot_product)

행렬내적 결과:
 [[ 58  64]
 [139 154]]


- 전치행렬

원행렬에서 행과 열의 위치를 교환한 원소로 구성한 행렬

행렬 A의 전치행렬 -> A^T

In [54]:
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치행렬:\n',transpose_mat)

A의 전치행렬:
 [[1 3]
 [2 4]]
