In [4]:
#numpy를 np라는 이름으로 불러온다.
import numpy as np

In [5]:
# array1이라는 변수에 [1,2,3]이라는 1차원 array를 대입한다. array함수는 파이썬의 다양한 인자를 입력받아서 ndarray로 변환한다.
array1=np.array([1,2,3])

# array1의 type는 ndarray이다.numpy의 기본 데이터 타입이다.
print('array1 type:' , type(array1))

# array1의 형태는 (3,)이다. 1차원 array이기 때문에 앞과 뒤 중 하나를 비워 놓는다.
print('array1 array 형태:' ,array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [6]:
# array2이라는 변수에 [[1,2,3],[2,3,4]]이라는 2차원 2*3행렬을 대입한다. 
array2=np.array([[1,2,3],[2,3,4]])

# array2의 type는 ndarray이다.numpy의 기본 데이터 타입이다.
print('array2 type:' , type(array2))

# array2의 형태는 (2,3)이다. 2차원 데이터를 표기한 것이다.
print('array2 array 형태:' ,array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [7]:
# array3이라는 변수에 [[1,2,3]]이라는 2차원 1*3행렬을 대입한다.
array3=np.array([[1,2,3]])

# array3의 type는 ndarray이다.numpy의 기본 데이터 타입이다.
print('array3 type:' , type(array3))

# array3의 형태는 (1,3)이다. 2차원 데이터를 표기한 것이다.
print('array3 array 형태:' ,array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [8]:
array1=np.array([1,2,3])
array2=np.array([[1,2,3],[2,3,4]])
array3=np.array([[1,2,3]])

# {}안에 format메서드를 사용해서 format 뒤에 값들을 괄호에 넣어서 출력한다.
# ndim함수는 array의 차원을 출력하는 것이다.
# {}안에 0,1,2는 format뒤 자료의 순서를 나타낸 것이다.
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [9]:
list1=[1,2,3]
print(type(list1))

# list를 array로 변환한다. type은 당연히 list에서 ndarray로 변환된다.
array1=np.array(list1)
print(type(array1))

# dtype은 array의 data type을 출력한다. array1은 모두 정수형 자료들을 가지고 있으므로 int형으로 표기된다.
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [10]:
list2=[1,2,'test']
# list를 array로 변환한다. 
array2=np.array(list2)
# array2는 정수형 자료와 string형 자료가 복합적으로 들어 있으므로 dtype이 이상하게 나온다.
print(array2, array2.dtype)

list3=[1,2,3.0]
# list를 array로 변환한다. 
array3=np.array(list3)
# array3는 정수형 자료와 실수형 자료가 복합적으로 들어 있으므로 dtype이 실수형으로 나온다.
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [11]:
# astype메서드: ndarray내 데이터값의 타입 변경

array_int=np.array([1,2,3])
# array_int의 dtype을 float로 변경 -> 자료도 실수형으로 표기가 됨
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

# array_int1의 dtype을 int로 변경 -> 자료 정수형으로 기기
array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
# array_float1의 dtype을 int로 변경-> 소수점에서 반올림해서 정수형으로 표기
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [12]:
# arange(n,m)메서드 : n부터 m미만의 정수를 데이터값으로 변환
# 0부터 9까지의 정수를 데이터값으로 변환
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [13]:
# zeros, ones: 0과 1의 정수를 데이터값으로 채운다.

#3*2 행렬의 데이터를 모두 0으로 채운다, dtype을 정수로 바꾼다.
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#3*2 행렬의 데이터를 모두 1로 채운다, dtype은 정해주지 않으면 기본적으로 실수형으로 나온다.
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [14]:
# reshape 메서드 : ndarray를 특정 차원 및 크기로 변경. 단, 자료의 숫자는 맞아야함 (자료가 10개라면 3*4형 같은 걸로는 변경 X)

# 0부터 9까지의 자료를 1차원으로 생성 
array1=np.arange(10)
print('array1:\n',array1)

# 1차원의 array1을 2*5행렬의 2차원으로 변경
array2=array1.reshape(2,5)
print('array2:\n',array2)

# 1차원의 array1을 5*2행렬의 2차원으로 변경 
array3=array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
array1=np.arange(10)
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
# reshape에 -1을 사용하는 경우 : array의 자료의 개수에 맞추어서 자동적으로 shape이 생성된다.

array1=np.arange(10)
print(array1)
# (-1,5) 행렬로 reshape -> 5열이 있고 데이터가 10개이므로 자동적으로 행은 2행으로 정해진다.
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
# (5,-1) 행렬로 reshape -> 5행이 있고 데이터가 10개이므로 자동적으로 열은 2열로 정해진다.
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

In [ ]:
# 당연히 10은 4로 나눌 수 없기에 아래의 코드는 오류가 발생한다.
array1=np.arange(10)
array4=array1.reshape(-1,4)

In [ ]:
# reshape 메서드로 차원 변경도 가능하다.

array1=np.arange(8)
array3d=array1.reshape((2,2,2))
#tolist 메서드는 array를 list자료형으로 변환한다.
print('array3d:\n', array3d.tolist())

# 2*2*2의 3차원 array를 2차원으로 변경
array5=array3d.reshape((-1,1))
print('array5:\n', array5.tolist())
print('array5 shape:' , array5.shape)

# 1차원 array를 2차원으로 변경
array6=array1.reshape((-1,1))
print('array6:\n', array6.tolist())
print('array6 shape:' , array6.shape)

In [ ]:
# numpy에서 ndarray내의 일부 데이터를 선택 : Indexing

array1=np.arange(1,10)
print('array1:', array1)
# array1에서 3번째 데이터 선택
value=array1[2]
print('value:', value)
print(type(value))
# array1에서 맨 뒤, 맨뒤에서 2번째 데이터 선택 (-는 제일 뒤로 넘어가는 것이다.)
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

In [ ]:
# array 내의 값 수정 : array[n]=m -> array의 n+1번째 데이터를 m으로 변경

array1=np.arange(1,10)
array1[0]=9
array1[8]=0
print('array1:', array1)

In [ ]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print(array2d)

# array의 데이터 추출 : array[n,m]은 n+1행 m+1열의 데이터를 추출하는 것이다.
print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

In [ ]:
# 슬라이싱 : array[n:m] -> array의 n번째 데이터부터 m-1번째 데이터까지 추출

array1=np.arange(1,10)
array3=array1[0:3]
print(array3)
print(type(array3))

In [ ]:
array1=np.arange(1,10)

# array의 처음부터 2번째 데이터까지
array4=array1[:3]
print(array4)

# array의 3번째 데이터부터 끝지지
array5=array1[3:]
print(array5)

# array의 모든 데터터
array6=array1[:]
print(array6)

In [ ]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)

# array2d의 0~1행, 0~1열 추출
print('array2d[0:2,0:2] \n', array2d[0:2,0:2])
# array2d의 1~2행, 0~2열 추출
print('array2d[1:3,0:3] \n', array2d[1:3,0:3])
# array2d의 0~2행, 모든 열 추출
print('array2d[1:3,:] \n', array2d[1:3,:])
# array2d의 모든 행, 모든 열 추출
print('array2d[:,:] \n', array2d[:,:])
# array2d의 처음~1행, 1~끝열 추출
print('array2d[:2,1:] \n', array2d[:2,1:])
# array2d의 처음~1행, 0열 추출 (열 칸에 오는 index가 0이므로 2차원 데이터가 아닌 1차원 데이터로 표시된다.)
print('array2d[:2,0] \n', array2d[:2,0], array2d[:2,0].shape)

In [ ]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)

# array2d의 0행 모두 추출, 뒤의 값이 없으므로 1차원 데이터로 표기된다.
print(array2d[0])
# array2d의 1행 모두 추출, 뒤의 값이 없으므로 1차원 데이터로 표기된다.
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

In [ ]:
# Fancy Indexing : array[[n,m],[N,M]] -> n~m행, N~M열 추출 (다른 것은 m-1, M-1이었는데 이건 끝까지 간다!!!)

array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
# array2d의 0~1행, 2열 추출
array3=array2d[[0,1],2]
print('array2d[[0,1],2]->', array3.tolist())
# array2d의 0~1행, 0~1열 추출
array4=array2d[[0,1],0:2]
print('array2d[[0,1],2]->', array4.tolist())
# array2d의 0~1행, 모든 열 추출
array5=array2d[[0,1]]
print('array2d[[0,1],2]->', array5.tolist())

In [ ]:
# Boolean indexing : array추출에서 조건 추가하고 조건에 맞는 것만 추출

array1d=np.arange(1,10)
# array1d에서 5보다 큰 데이터들만 추출
array3=array1d[array1d>5]
print('array1d>5 boolean indexing 결과 값:', array3)

# array1d에서 주어진 조건대로 True, False 출력
array1d>5

In [ ]:
array1d=np.arange(1,10)

# boolean index로 필터링 : True, False라는 결과를 미리 만들어 놓고, True에 해당하는 자료들만 추출한다.
boolean_indexes=np.array([False, False, False, False, False, True, True, True, True])
array3=array1d[boolean_indexes]
print('boolean index로 필터링 결과:', array3)

In [ ]:
array1d=np.arange(1,10)

# array1d의 6,7,8,9번째 데이터 추출
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 index로 필터링 결과:', array4)

In [ ]:
# 행렬의 정렬 

org_array=np.array([3,1,9,5])
print('원본 행렬: ', org_array)

#np.sort() 메서드는 원 행렬을 유지하고 행렬의 정렬된 행렬을 반환한다. (오름차순)
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 호출 후 반환된 원본 행렬: ', org_array)

# ndarray.sort() 메서드는 원 행렬 자체를 정렬한 형태로 반환한다. (원 행렬이 없어지고 None 값이 된다.)
sort_array2=org_array.sort()
print('org.array.sort() 호출 후 반환된 정렬 행렬: ', sort_array2)
print('org.array.sort() 호출 후 반환된 원본 행렬: ', org_array)

In [ ]:
org_array=np.array([3,1,9,5])
print('원본 행렬: ', org_array)

# 내림차순으로 정렬 : [::-1] 사용
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

In [ ]:
# 행렬이 2차원 이상일 경우 정렬: axis=0(행), axis=1(열)로 정렬

array2d=np.array([[8,12],
                  [7,1]])
# row 방향으로 정렬 (오름차순)
sort_array2d_axis0=np.sort(array2d,axis=0)
print('row 방향으로 정렬:\n', sort_array2d_axis0)
# column 방향으로 정렬 (내림차순)
sort_array2d_axis1=np.sort(array2d,axis=1)
print('column 방향으로 정렬:\n', sort_array2d_axis1)

In [ ]:
# 정렬 행렬의 원본 행렬 index 반환 : np.argsort() 메드드

org_array=np.array([3,1,9,5])
# org_array를 정렬 시 org_array의 index를 sort_indices에 행렬 형태로 대입
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

In [ ]:
# 마찬가지로 [::-1] 하면 내림차순으로 반환된다.
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

In [ ]:
import numpy as np

name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78,95,84,98,88])

# sort_indices_asc: score_array를 오름차순으로 정렬 후 그 위치 정보를 반환
# 이후 name_array[sort_indices_asc]를 하면 성적 오름차순대로 이름이 반환
sort_indices_asc=np.argsort(score_array)
print('성적 오름차순으로 정렬 시 score_array의 index:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

In [16]:
# 행렬의 내적: np.dot(A,B) : A와 B 내적

A=np.array([[1,2,3],
           [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])
doc_product=np.dot(A,B)
print('행렬 내적 결과:\n', doc_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [18]:
# 행렬의 전치행렬 구하기: np.transpose(A)

A=np.array([[1,2],
           [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
