# 넘파이

### 넘파이 ndarray 개요

In [1]:
import numpy as np

데이터 타입: ndarray
array(): ndarray로 변환

In [2]:
#array():ndarray로 변환
#array.shape : array의 행,열 수를 튜플 형태로
array1=np.array([1,2,3])   
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)   #1차원

array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)   #2차원

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


### ndarray의 데이터 타입

> 숫자형: int, float, unsigned int, float, complex/ 문자열 값 / 불 값  
> ndarray내의 데이터 타입은 같은 데이터 타입만 가능 -> 섞여있으면 더 큰 데이터 타입으로 형 변환  
> array.dtype: array의 데이터 타입 확인  
> array.astype() : 데이터 타입 변경 ex) array.astype('int32') int32로 변경  --> 메모리 절약

In [4]:
list1 =[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)  

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
list2= [1,2,'test']
array2= np.array(list2)   #int->string
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)   #int->float
print(array3,array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
#int32 -> float64 -> int32
array_int = np.array([1,2,3])
array_float= array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

> np.arange(stop), np.arange(start, stop)

In [7]:
sequence_array= np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

sequence_array2= np.arange(2,10)  #start, stop
print(sequence_array2)
print(sequence_array2.dtype,sequence_array2.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[2 3 4 5 6 7 8 9]
int32 (8,)


> np.zeros(shape) : 0으로 채운 ndarray  
> np.ones(shape) : 1로 채운 ndarray  
> dtype 안정하면 float64로 

In [8]:
zero_array= np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()
> array.reshape(n,m)

In [9]:
array1=np.arange(10)
print('array1:\n', array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)
      

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
#array1.reshape(4,3) reshape 불가능으로 오류 발생

> array.reshape(-1,n) or (n,-1): 호환되는 shape으로 변환

In [11]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:',array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [12]:
# array1=np.arange(10)
# array4=array1.reshape(-1,4) 오류 발생

> reshape(-1,1)  
> 3차원을 2차원으로, 2차원을 1차원으로  
> array.tolist() 메서드: 리스트 자료형으로 변환


In [13]:
array1=np.arange(8)
array3d= array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())  #이해를 위해 리스트로 변경

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
1. 특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환됩니다.
2. 슬라이싱(Slicing): 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식입니다. ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환합니다. 예를 들어 1:5라고 하면 시작 인덱스 1과 종료 인덱스 4까지에 해당하는 ndarray를 반환합니다.
3. 펜시 인덱싱(Fancy indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환합니다.
4. 불린 인덱싱(Boolean indexing): 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환합니다.

> 단일값 추출: 타입-ndarray의 데이터값  ex)numpy.int32

In [14]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1,stop=10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [15]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번쩨 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번쩨 값: 8


In [16]:
#ndarray내의 데이터 값 수정
array1[0]=9
array1[8]=0
print('array1:' ,array1)

array1: [9 2 3 4 5 6 7 8 0]


In [17]:
#다차원 ndarray에서 단일 값 추출
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, column=0) index가 가리키는 값:', array2d[0,0])
print('(row=0, column=1) index가 가리키는 값:', array2d[0,1])
print('(row=1, column=0) index가 가리키는 값:', array2d[1,0])
print('(row=2, column=2) index가 가리키는 값:', array2d[2,2])
#axis0은 row, axis1은 column로 이해하면 쉬우나 [axis1=0,axis1=1] 이런 방식이 올바른 표현

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, column=0) index가 가리키는 값: 1
(row=0, column=1) index가 가리키는 값: 2
(row=1, column=0) index가 가리키는 값: 4
(row=2, column=2) index가 가리키는 값: 9


> 슬라이싱-ndarray타입

In [18]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))


[1 2 3]
<class 'numpy.ndarray'>


In [19]:
# ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
array1=np.arange(1,10)
array4=array1[:3]
print(array4)


#':'기호 뒤에 종료 인덱슬를 생략하면 자동으로 맨 마지막 인덱스로 간주
array5=array1[3:]
print(array5)


#':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주
array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [22]:
#2차원 슬라이싱
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0]) #1차원으로 반환

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [23]:
print(array2d[0]) # 2차원 뒤에 오는 인덱스를 없애면 1차원 ndarray로 반환
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape,'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


> 팬시 인덱싱(Fancy Indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환
> 

In [4]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2] #(0,2),(1,2)
print('array2d[[0,1],2] => ', array3.tolist())

array4=array2d[[0,1],0:2] #((0,0),(0,1)),((1,0),(1,1))
print('array2d[[0,1],0:2] => ', array4.tolist())

array5=array2d[[0,1]] #((0,:),(1,:))
print('array2d[[0,1]] => ', array5.tolist())  



array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


> 불린 인덱싱(Boolean indexing): 조건과 필터링을 동시에
> > Step1: array1d > 5와 같이 ndarray의 필터링 조건을 [] 안에 기재  
> > Step2: False 값은 무시하고 True 값에 해당하는 인덱스값만 저장(유의해야 할 사항은 True 값 자체인 1을 저장하는 것이 아니라 True 값을 가진 인덱스를 저장한다는 것입니다.)  
> > Step3: 저장된 인덱스 데이터 세트로 ndarray 조회

In [5]:
array1d=np.arange(1,10)
# [] 안에 array1d > 5 Boolean indexing 을 적용
array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값 :',array3)

array1d>5 불린 인덱싱 결과 값 : [6 7 8 9]


In [6]:
array1d>5   #False, True로 이루어진 ndarray 객체 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [11]:
#불린 인덱스와 일반 인덱스와 결과 동일
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :',array3)

indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과 :',array4)

불린 인덱스로 필터링 결과 : [6 7 8 9]
일반 인덱스로 필터링 결과 : [6 7 8 9]


###행렬의 정렬 - sort()와 argsort()
>np.sort(): 넘파이에서 sort()를 호출-원 행렬 그대로 유지, 원 행렬의 정렬된 형태 반환(오름차순 정렬)  
>ndarray.sort(): 행렬 자체에서 sort()를 호출-원 행렬 자체를 정렬, 반환 값 None (오름차순 정렬)

In [3]:
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)

#np.sort()로 정렬-원 행렬 그대로 유지
sort_array1=np.sort(org_array)
print('np.sort()로 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)

#ndarray.sort()로 정렬-원 행렬 자체를 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2) #반환 값 None
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort()로 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [4]:
#내림차순 정렬: [::-1] 적용
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [5]:
# 2차원 이상일 경우  
array2d=np.array([[8,12],
                 [7,1]])

#np.sort(A,axis=0) 세로 정렬
sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

#np.sort(A,axis=1) 가로 정렬
sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)



로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


> 정렬된 행렬의 인덱스를 반환하기-np.argsort()
> 1. np.argsort(A) 호출
> 2. 정렬된 행렬의 원본 행렬 인덱스 추출
> 3. 정렬된 행렬의 원본 행렬 인덱스 반환

In [6]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [7]:
#내림차순 인덱스 구하기 - [::-1] 이용
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [8]:
import numpy as np

name_array=np.array(['John', 'Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print( '성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])  # name_array[0 2 4 1 3]

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산- 행렬 내적과 전치 행렬 구하기
> 행렬 내적(행렬 곱): np.dot()

In [9]:
#np.dot()
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


>전치 행렬: 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬-np.transpose(A)

In [10]:
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
