In [69]:
#넘파이 불러오기 np는 편리하게 활용하기 위함
import numpy as np

In [4]:
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [5]:
array2=np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [6]:
#array1과는 다르게 대괄호가 한번 더 있음
array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [7]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [71]:
#ndarray의 데이터 타입 알아보기 
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [75]:
#중간에 문자형이 들어가 있을 경우
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

#중간에 float포함
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [10]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)
                            

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [11]:
#ndarray편리하게 생성
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [12]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [77]:
#ndarray 차원 크기 변경 reshape()
array1 =  np.arange(10)
print('array1:\n', array1)
#2행 5열
array2 =  array1.reshape(2,5)
print('array2:\n', array2)
#5행 2열
array3 =  array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
array1.reshape(4,3)
#오류

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
array1 =  np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

In [ ]:
array1 = np.arange(8)
array3d =  array1.reshape((2,2,2))

#3차원->2차원
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원->2차원
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

In [ ]:
#단일값추출
#1부터 9까지의 1차원 ndarry생성 
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

In [ ]:
print('맨 뒤의 값:',array1[-1], '맨 뒤에서 두 번쨰 값:', array1[-2])

In [ ]:
array1[0]=9
array1[8]=0
print('array1:', array1)

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

#axis0=row, axis1=column

In [ ]:
#슬라이싱
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

In [15]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [79]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)
#원하는 정보 뽑아내기 
print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [19]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [25]:
#팬시 인덱싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2[[0,2], 2]=>', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2[[0,1], 0:2]=>', array4.tolist())

array5 = array2d[[0,1]]
print('array2[0,1]=>', array5.tolist())

array2[[0,2], 2]=> [3, 6]
array2[[0,1], 0:2]=> [[1, 2], [4, 5]]
array2[0,1]=> [[1, 2, 3], [4, 5, 6]]


In [73]:
#불린 인덱싱
array1d = np.arange(start=1, stop=10)
# []안에 array1d>5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d>5불린 인덱싱 결과 값 :', array3)

array1d>5불린 인덱싱 결과 값 : [6 7 8 9]


In [29]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [31]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스 필터링 결과:', array3)

불린 인덱스 필터링 결과: [6 7 8 9]


In [33]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스 필터링 결과:', array4)

일반 인덱스 필터링 결과: [6 7 8 9]


In [41]:
#행렬정렬
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
#np.sort로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort 호출 후 원본 행렬:', org_array)
#ndarray.sort로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort 호출 후 원본 행렬: [1 3 5 9]


In [45]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [49]:
array2d = np.array([[8,12], [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼방향으로 정렬:\n', sort_array2d_axis1)


로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [51]:
#정렬된 행렬의 인덱스를 반환하기
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)


<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [55]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [59]:
import numpy as np

name_array =  np.array(['john', 'miker', 'sarah', 'kate', 'samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['john' 'sarah' 'samuel' 'miker' 'kate']


In [63]:
#선형대수 연산
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8], [9,10], [11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [67]:
#전치 행렬
C=np.array([[1,2,], [3,4]])
transpose_mat = np.transpose(C)
print('C의 전치 행렬:\n', transpose_mat)

C의 전치 행렬:
 [[1 3]
 [2 4]]
