In [1]:
import numpy as np
# numpy 모듈을 간단하게 약어로 표현

In [2]:
array1 = np.array([1,2,3])
print('arrat1 type:', type(array1))
print('array1 arrat 형태:',array1.shape)
#1차원에 3개의 데이터

array2=np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:',array2.shape)
#2차원으로 2row, 3column

array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)
#2차원으로 1row, 3column

print('array1:{0}차원, array2:{1}차원, array3:{2}차원'.format(array1.ndim,array2.ndim,array3.ndim))
#ndarray.ndim은 각 array의 차원을 확인하는 함수

arrat1 type: <class 'numpy.ndarray'>
array1 arrat 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1:1차원, array2:2차원, array3:2차원


In [3]:
list1=[1,2,3]
print(type(list1))
array1 = np.array(list1)
#리스트를 ndarray로 변경
print(type(array1))
print(array1,array1.dtype)
#array1의 데이터 타임 확인

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [4]:
list2=[1,2,'test']
array2=np.array(list2)
print(type(array2))
print(array2, array2.dtype)
#ndarray는 데이터 값이 모두 같은 데이터 타입이어햐 해 다른 데이터 타입들이 섞일 경우 데이터 타입이 더 큰 데이터 타입으로 변환됨

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

<class 'numpy.ndarray'>
['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [5]:
# 데이터 타입을 바꾸는 과정, float를 int형으로 변경할 경우 소수점 이하는 사라짐
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [6]:
#aronge()는 array를 range()로 표현, 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터 값으로 변환해줌
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [7]:
#zeros()는 모든 값을 0으로 채운 해당 shape를 가진 ndarray로 변환해줌
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)
#ones()는 모든 값을 1로

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [8]:
#reshape()는 ndarray를 특정 차원 및 크기로 변환함, 원하는 크기를 함수 인자로 부여하면 됨
array1=np.arange(10)
print('array:\n',array1)

array2=array1.reshape(2,5)
print('array:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

array:
 [0 1 2 3 4 5 6 7 8 9]
array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [9]:
array1.reshape(4,3)
#지정된 사이즈로 변경이 불가능하면 오류 발생함

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
# -1을 사용해 원래 ndarray와 호환되는 새로운 shape로 변환해 줌
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:',array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:',array3.shape)

In [ ]:
array1=np.arange(10)
array4=array1.reshape(-1,4)
#마찬가지로 호환될 수 없는 형태는 변환 불가능

In [10]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())
#tolist()는 리스트 자료형으로 변환하는 메서드, print로 출력 시 시각적으로 이해하기 더 쉬움

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [11]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [12]:
print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두 번째 값:',array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [13]:
# 단일 인덱스를 이용해 ndarray 내의 데이터 값 수정 가능
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [14]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [15]:
# :를 이용해 연속한 데이터를 슬라이싱 해 추출 가능, : 사이의 시작, 종료 인덱스는 생략 가능
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [16]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [17]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

#2차원에서는 ,로 로우와 칼럼 인덱스를 나눔, 전이 row 후가 col
print('array2d[0:2, 0:2]\n',array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n',array2d[1:3,0:3])
print('array2d[1:3, :]\n',array2d[1:3, :])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2, 0]\n',array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [18]:
# 2차원 뒤에 오는 인덱스를 없애면 1차원 ndarray를 변환함(row)
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [19]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
#팬시 인덱싱은 리스트나 ndarray로 인덱스 집합을 지정하면 그 위치의 데이터를 ndarray로 변환

array3=array2d[[0,1],2]
print('array2d[[0.1],2]=>',array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

array2d[[0.1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


In [20]:
#불린 인덱싱은 조건 필터링과 검색 동시에 가능
#[] 내에 조건문을 그대로 작성 시 작동
array1d=np.arange(start=1,stop=10)
# []안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [21]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [22]:
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :',array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [23]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [24]:
#np.sort()는 넘파이에서 sort()를 호출, ndarray.sort()는 행렬 자체에서 sort()를 호출
#전자는 원 행렬은 유지한 채 원 행렬의 정렬된 행렬을 반환, 후자는 원 행렬 자체를 정렬한 형태로 변환하고 반환 값은 None
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)
# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [25]:
#기본적으로 오름차순으로 정렬, 내림차순으로 정렬하기 위해서는 [::-1] 적용해야 함
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [26]:
#2차원 이상일 경우 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬 수행 가능
array2d = np.array([[8,12],
                  [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [27]:
#np.argsort()는 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 이용
#정렬 행렬의 원본 행렬 인덱스를 ndarrayn 형으로 반환함
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [28]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [29]:
import numpy as np

name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [30]:
#np.dot()은 두 행렬의 내적을 구할 시 이용
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [31]:
#transpose()는 전치행렬 구할 때 이용
A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
